name: Generate GitHub Contribution Grid Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake Animation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate SVG with Platane/snk
        uses: Platane/snk@v3
        with:
          github_user_name: dataspieler12345
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push generated SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
